[tool.poetry]
name = "manifest_transformer"
version = "0.1.0"
description = ""
authors = ["Ian Vermes <iv3@sanger.ac.uk>"]
readme = "README.md"
packages = [{include = "manifest_transformer.py"}]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pre-commit = "^3.3.2"
ipython = "^8"
pytest = "^7.3.2"
pandas = "^2.0.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
